version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - '.:/code'
    external_links:
      - redis

    #network_mode: bridge
    networks: 
      - mynet
networks:
    mynet:
      external: true
